export enum DISCIPLINES {
  THREED = '3D',
  UX = 'UX',
  VR = 'VR',
  ARCHITECTURE = 'Architecture',
  BRANDING = 'Branding',
  BUSINESS = 'Business',
  COPYWRITING = 'Copywriting',
  CREATIVITY = 'Creativity',
  DESIGN = 'Design',
  DEVELOPMENT = 'Development',
  ECOMMERCE = 'Ecommerce',
  ENTREPRENEURSHIP = 'Entrepreneurship',
  EXPERIMENTAL = 'Experimental',
  FASHION = 'Fashion',
  GAMES = 'Games',
  ILLUSTRATION = 'Illustration',
  INNOVATION = 'Innovation',
  LEADERSHIP = 'Leadership',
  MOTION = 'Motion',
  MUSIC = 'Music',
  PHOTOGRAPHY = 'Photography',
  PORTFOLIOS = 'Portfolios',
  PRODUCT = 'Product',
  PUBLISHING = 'Publishing',
  REMOTE = 'Remote',
  STRATEGY = 'Strategy',
  SUSTAINABILITY = 'Sustainability',
  WRITING = 'Writing',
}

export enum DAYS_OF_THE_WEEK {
  MONDAY = 'monday',
  TUESDAY = 'tuesday',
  WEDNESDAY = 'wednesday',
  THURSDAY = 'thursday',
  FRIDAY = 'friday',
  SATURDAY = 'saturday',
  SUNDAY = 'sunday',
}

export enum TIMEZONES {
  GMT_MINUS_1 = 'GMT -1',
  GMT = 'GMT',
  GMT_PLUS_1 = 'GMT +1',
}
