import { SeedData } from './index'

export const testData: SeedData = {
  users: [
    {
      email: 'josh@companion.studio',
      userId: '0c802d2c-a791-44d2-affb-82cc4181bb9c',
      password: '$2b$10$fAumKMth8e08OK2BROsWmep2s15X6fDELdLwEZ36urI8OfwgUzw2.',
      role: 'PAIRER',
      verificationCode: 'p/u+5OGxvmeH17Uxb/OMtUnGfhfh0TWnk+/0yHtReXs=',
      verificationTimeout: '2022-02-01T10:53:51Z',
      verified: false,
      personalKey: 'apples',
      createdAt: new Date(),
    },
    {
      email: 'myles@companion.studio',
      userId: '0c802d2c-a791-44d2-affb-82cc4181cc9c',
      password: '$2b$10$fAumKMth8e08OK2BROsWmep2s15X6fDELdLwEZ36urI8OfwgUzw2.',
      role: 'PAIRER',
      verificationCode: 'p/u+5OGxvmeH17Uxb/OMtUnGfhfh0TWnk+/0yHtReXs=',
      verificationTimeout: '2022-02-01T10:53:51Z',
      verified: false,
      personalKey: 'banana',
      createdAt: new Date(),
    },
  ],
  sessions: [
    {
      id: '123',
      createdAt: new Date(),
      firstName: 'josh',
      lastName: 'ellis',
      email: 'ellis@companion.studio',
      jobTitle: 'designer',
      portfolio: '',
      timezone: '',
      appointment: '',
      subjects: [],
      status: 'ACTIVE',
      pairerId: '0c802d2c-a791-44d2-affb-82cc4181cc9c',
    },
    {
      id: '456',
      createdAt: new Date(),
      firstName: 'John',
      lastName: 'smith',
      email: 'smithy@companion.studio',
      jobTitle: 'producer',
      portfolio: '',
      timezone: '',
      appointment: '',
      subjects: [],
      status: 'ACTIVE',
      pairerId: '0c802d2c-a791-44d2-affb-82cc4181cc9c',
    },
    {
      id: '789',
      createdAt: new Date(),
      firstName: 'Davey',
      lastName: 'Slapps',
      email: 'slapper@companion.studio',
      jobTitle: 'Printer Specialist',
      portfolio: '',
      timezone: '',
      appointment: '',
      subjects: [],
      status: 'CANCELLED',
      pairerId: '0c802d2c-a791-44d2-affb-82cc4181cc9c',
    },
    {
      id: '001',
      createdAt: new Date(),
      firstName: 'Scooby',
      lastName: 'Doo',
      email: 'dooby@companion.studio',
      jobTitle: 'Squirell Hunter',
      portfolio: '',
      timezone: '',
      appointment: '',
      subjects: [],
      status: 'COMPLETE',
      pairerId: '0c802d2c-a791-44d2-affb-82cc4181cc9c',
    },
  ],
  messages: [
    {
      id: 'm-000',
      createdAt: new Date(),
      message: 'hello I am 000 message',
      sessionId: '123',
    },
    {
      id: 'm-001',
      createdAt: new Date(),
      message: 'hello I am 456 message',
      sessionId: '456',
    },
    {
      id: 'm-002',
      createdAt: new Date(),
      message: 'hello I am 789 message',
      sessionId: '789',
    },
    {
      id: 'm-003',
      createdAt: new Date(),
      message: 'hello I am 001 message',
      sessionId: '001',
    },
  ],
}

export const passwords = [
  {
    email: 'josh@companion.studio',
    userId: '0c802d2c-a791-44d2-affb-82cc4181bb9c',
    password: '6!u.YylCKG01V]y}9+$O',
  },
  {
    email: 'myles@companion.studio',
    userId: '0c802d2c-a791-44d2-affb-82cc4181cc9c',
    password: '6!u.YylCKG01V]y}9+$O',
  },
]
