version: '3.8'
services:
  pairup-api:
    depends_on:
      - pairupdb
    environment:
      DATABASE_URL: postgres://postgres:postgres@pairupdb:5432/pairup
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./packages/api/:/api/packages/api
      - ./packages/shared/:/api/packages/shared
  # Postgres
  pairupdb:
    image: postgres:latest
    container_name: pairupdb
    restart: always
    ports:
      # Accessible from the host at port :35432
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pairup
    # Make sure log colors show up correctly
    tty: true
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: pairup-docker-db
