version: '3'
services:
  pairup-api:
    container_name: pairup-prod
    restart: always
    env_file:
      - packages/api/.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
