name: 🐞 Bug Report 🐛
description: File a bug report
title: '[bug]: '
labels: ['template: potential bug']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filing a bug report!
  - type: checkboxes
    id: area
    attributes:
      label: Which area does this apply too?
      options:
        - label: 'native (most common unless you're a developer)'
        - label: 'api'
        - label: 'cms'
        - label: 'web'
  - type: input
    attributes:
      label: What version of the app are you using?
  - type: textarea
    attributes:
      label: "What's Wrong?"
      description: A concise description of what you expected to happen
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behaviour
      description: What you expected to happen
    validations:
      required: true
