-- AlterTable
ALTER TABLE "Session" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "lastName" SET DEFAULT E'',
ALTER COLUMN "jobTitle" SET DEFAULT E'',
ALTER COLUMN "portfolio" SET DEFAULT E'';

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
