import {
  SIGNUP_ACCOUNT_DETAIL_FIELD_NAMES,
  SIGNUP_PERSONAL_DETAIL_FIELD_NAMES,
  SIGNUP_AVAILABILITY_FIELD_NAMES,
} from '@pairup/shared'

export enum SIGNUP_STAGE {
  START = 'START',
  ACCOUNT_DETAILS = 'ACCOUNT_DETAILS',
  PERSONAL_DETAILS = 'PERSONAL_DETAILS',
  AVAILABILITY = 'AVAILABILITY',
}

export {
  SIGNUP_ACCOUNT_DETAIL_FIELD_NAMES,
  SIGNUP_PERSONAL_DETAIL_FIELD_NAMES,
  SIGNUP_AVAILABILITY_FIELD_NAMES,
}
