name: Deploy Api
on:
  push:
    branches:
      - 'main'
    paths:
      - 'packages/api/**'
      - 'packages/shared/**'
jobs:
  prod:
    name: 'Deploy'
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Read app name
        uses: SebRollen/toml-action@v1.0.0
        id: app_name
        with:
          file: 'fly.toml'
          field: 'app'

      - name: Deploy Production
        uses: superfly/flyctl-actions@1.3
        with:
          args: 'deploy --image registry.fly.io/${{ steps.app_name.outputs.value }}:${{ github.ref_name }}-${{ github.sha }}'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
