name: Deploy
on:
  push:
    branches:
      - 'main'
jobs:
  changes:
    name: 'Detect changes'
    runs-on: ubuntu-18.04
    # Set job outputs to values from filter step
    outputs:
      api: ${{ steps.filter.outputs.api }}
      cms: ${{ steps.filter.outputs.cms }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            api:
              - 'packages/api/**'
              - 'packages/shared/**'
            cms:
              - 'packages/cms/**'
              - 'packages/shared/**'

  api:
    name: 'Deploy Api'
    runs-on: ubuntu-18.04
    needs: changes
    if: ${{ needs.changes.outputs.api == 'true' }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Read app name
        uses: SebRollen/toml-action@v1.0.0
        id: app_name
        with:
          file: 'fly.toml'
          field: 'app'

      - name: Deploy Production
        uses: superfly/flyctl-actions@1.3
        with:
          args: 'deploy'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  # cms:
  #   name: 'Deploy CMS'
  #   runs-on: ubuntu-18.04
  #   needs: changes
  #   if: ${{ needs.changes.outputs.cms == 'true' }}
  #   steps:
  #     - name: Cancel Previous Runs
  #       uses: styfle/cancel-workflow-action@0.9.1

  #     - name: Checkout
  #       uses: actions/checkout@v2
